name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@b80cbe5c81391f01badbe906f05ec34d7aef53c5 # v1.16.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        uses: spotdemo4/bumper@415b3b6011a9242aa3becbc24413ad321d37b9f7 # v0.7.3
        with:
          force: ${{ inputs.force }}
          files: |-
            .github/README.md
