name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@59e9eaa3d67e67b17b92ce2c6ffc83deed76fc91 # v1.11.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        uses: spotdemo4/bumper@47e22c10f86c5db6679c74ac50c223973daf93ab # v0.5.0
        with:
          force: ${{ inputs.force }}
          files: |-
            .github/README.md
