name: bump

on:
  schedule:
    - cron: "0 22 * * 1-5" # every weekday at 22:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force bump"
        required: false
        type: choice
        default: "true"
        options:
          - "true"
          - "false"

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          app_id: ${{ vars.CLIENT_ID }}
          app_key: ${{ secrets.PRIVATE_KEY }}
          fetch_depth: 0
          shell: bump

      - name: Bump
        uses: spotdemo4/bumper@32534ba92eb765a5dd0d22d2ee2064748d0a2042 # v0.2.5
        with:
          force: ${{ inputs.force }}
          files: |-
            .github/README.md
