name: check

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

permissions:
  contents: read

jobs:
  check:
    if: ${{ ! startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@690fe67ad00aa917e156d970e6dd3c3ef4db33c5 # v1.8.2

      - name: Run checks
        if: ${{ steps.init.outputs.duplicate != 'true' }}
        run: nix flake checkk

  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@0261e3554149588c911e068afc042bdc0627f227 # v3.12.2
        with:
          extra-conf: |
            lazy-trees = false

      - run: determinate-nixd version

      - name: Bundle
        run: nix bundle --bundler github:NixOS/bundlers#toDEB -o result
