name: release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@59e9eaa3d67e67b17b92ce2c6ffc83deed76fc91 # v1.11.0

      - name: Check
        run: nix flake check

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          generate_release_notes: true

  binary:
    needs: check
    strategy:
      matrix:
        target: [x86_64-windows, x86_64-linux, aarch64-linux, aarch64-darwin]
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@59e9eaa3d67e67b17b92ce2c6ffc83deed76fc91 # v1.11.0

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#deno-${{ matrix.target }} -o bundle

      - if: matrix.target != 'x86_64-windows'
        name: Package (tar.xz)
        run: tar -cJhf "svelte-template-${GITHUB_REF_NAME#v}-${{ matrix.target }}.tar.xz" bundle

      - if: matrix.target == 'x86_64-windows'
        name: Package (zip)
        run: zip -r "svelte-template-${GITHUB_REF_NAME#v}-${{ matrix.target }}.zip" bundle

      - name: Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: svelte-template-*-${{ matrix.target }}.*

  image:
    needs: check
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@59e9eaa3d67e67b17b92ce2c6ffc83deed76fc91 # v1.11.0
        with:
          shell: release

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#docker-stream -o result

      - name: Release
        run: |
          ./result | gzip --fast | skopeo --insecure-policy copy \
            --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker-archive:/dev/stdin \
            "docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}-${{ steps.init.outputs.system }}"

  manifest:
    needs: image
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        id: init
        uses: spotdemo4/nix-init@59e9eaa3d67e67b17b92ce2c6ffc83deed76fc91 # v1.11.0

      - name: Login
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"

      - name: Create manifest
        run: |
          VERSION="ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}"
          LATEST="ghcr.io/${{ github.repository }}:latest"

          docker manifest create "${VERSION}" \
            "${VERSION}-x86_64-linux" \
            "${VERSION}-aarch64-linux" \
            "${VERSION}-aarch64-darwin"

          docker manifest annotate "${VERSION}" "${VERSION}-x86_64-linux" --arch amd64 --os linux
          docker manifest annotate "${VERSION}" "${VERSION}-aarch64-linux" --arch arm64 --os linux
          docker manifest annotate "${VERSION}" "${VERSION}-aarch64-darwin" --arch arm64 --os darwin

          docker manifest create "${LATEST}" \
            "${VERSION}-x86_64-linux" \
            "${VERSION}-aarch64-linux" \
            "${VERSION}-aarch64-darwin"

          docker manifest annotate "${LATEST}" "${VERSION}-x86_64-linux" --arch amd64 --os linux
          docker manifest annotate "${LATEST}" "${VERSION}-aarch64-linux" --arch arm64 --os linux
          docker manifest annotate "${LATEST}" "${VERSION}-aarch64-darwin" --arch arm64 --os darwin

          docker manifest push "${VERSION}"
          docker manifest push "${LATEST}"
