name: release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  packages: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Run checks
        run: nix flake check

  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Build
        run: nix nario export --format 2 --recursive .# > template.nario

      - name: Upload nario
        uses: actions/upload-artifact@v4
        with:
          name: template-nario
          path: template.nario

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          generate_release_notes: true

  linux-amd64:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Download nario
        uses: actions/download-artifact@v5
        with:
          name: template-nario

      - name: Load nario
        run: nix nario import < template.nario

      - name: Bwrap Info
        id: bwrap
        run: |
          BWRAP_PATH=$(nix shell nixpkgs#bubblewrap \
            --inputs-from . \
            --command bash \
            -c "which bwrap")
          echo "bwrap_path=${BWRAP_PATH}" >> $GITHUB_OUTPUT
          echo "bwrap path: ${BWRAP_PATH}"

      - name: Git Info
        id: git
        run: |
          GIT_PATH=$(which git)
          echo "git_path=${GIT_PATH}" >> $GITHUB_OUTPUT
          echo "git path: ${GIT_PATH}"

      - name: Bundle
        env:
          NP_RUNTIME: bwrap
          NP_BWRAP: ${{ steps.bwrap.outputs.bwrap_path }}
          NP_GIT: ${{ steps.git.outputs.git_path }}
        run: nix bundle --bundler github:DavHau/nix-portable -o result .#

      - name: Rename
        id: rename
        run: |
          FILE_LINK=$(find -L result -type f -print -quit)
          FILE_REAL=$(readlink -f "${FILE_LINK}")
          ln -s "${FILE_REAL}" template-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64

  linux-amd64-deb:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Download nario
        uses: actions/download-artifact@v5
        with:
          name: template-nario

      - name: Load nario
        run: nix nario import < template.nario

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toDEB -o result .#
          cp result/*.deb template-linux-amd64.deb

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64.deb

  linux-amd64-rpm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Download nario
        uses: actions/download-artifact@v5
        with:
          name: template-nario

      - name: Load nario
        run: nix nario import < template.nario

      - name: Bundle
        run: |
          nix bundle --bundler github:NixOS/bundlers#toRPM -o result .#
          cp result/*.rpm template-linux-amd64.rpm

      - name: Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          files: template-linux-amd64.rpm

  container:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@63cc315d93acb3b914827e4ecd6c94d3358986f6 # v1.7.1

      - name: Download nario
        uses: actions/download-artifact@v5
        with:
          name: template-nario

      - name: Load nario
        run: nix nario import < template.nario

      - name: Bundle
        run: nix bundle --bundler github:spotdemo4/nur#toDockerStream -o result .#

      - name: Release
        run: |
          ./result \
          | gzip --fast \
          | nix shell nixpkgs#skopeo \
            --inputs-from . \
            --command skopeo copy \
            --dest-creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            docker-archive:/dev/stdin \
            docker://ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME#v}
