name: test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bundle-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@7ec16f2c061ab07b235a7245e06ed46fe9a1cab6 # v31

      - run: nix bundle --bundler github:NixOS/bundlers#toDEB -o result

  bundle-detsys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@0261e3554149588c911e068afc042bdc0627f227 # v3.12.2

      - run: determinate-nixd version

      - run: nix bundle --bundler github:NixOS/bundlers#toDEB -o result

  bundle-detsys-no-lazy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@0261e3554149588c911e068afc042bdc0627f227 # v3.12.2
        with:
          extra-conf: lazy-trees = false

      - run: determinate-nixd version

      - run: nix bundle --no-lazy-trees --bundler github:NixOS/bundlers#toDEB -o result
