name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  svelte:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          shell: vulnerable

      - name: Run npm audit
        run: npm audit --audit-level moderate

  nix:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

      - name: Build
        run: nix build -o result

      - name: Run vulnix
        uses: spotdemo4/vulnix-action@c614a37ec8850272bf58e0f821f3028aa32e5c4b # v1.0.1
        with:
          path: result
          score: 7

  actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@0a2f62e3b132c09b144b6957976f538f79fc81a2 # v1.10.0
        with:
          shell: vulnerable

      - name: Run octoscan
        run: octoscan scan --verbose .github
