name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  svelte:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d96e51032eab0e79b908192bcf66ed723140d0b1 # v1.8.4
        with:
          shell: vulnerable

      - name: npm audit
        run: npm audit --audit-level moderate

  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d96e51032eab0e79b908192bcf66ed723140d0b1 # v1.8.4
        with:
          shell: vulnerable

      - name: flake-checker
        run: flake-checker -f

      - name: build
        run: nix build -o result

      - name: vulnix
        uses: spotdemo4/vulnix-action@c614a37ec8850272bf58e0f821f3028aa32e5c4b # v1.0.1
        with:
          path: result
          score: 7

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@d96e51032eab0e79b908192bcf66ed723140d0b1 # v1.8.4
        with:
          shell: vulnerable

      - name: octoscan
        run: |
          octoscan scan --verbose .github
          octoscan scan --verbose .gitea
