name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  svelte:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8ea47d849953af36820bf44487a3ce7baf08e25e # v1.14.0
        with:
          shell: vulnerable

      - name: Run npm audit
        run: npm audit --audit-level moderate

  nix:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8ea47d849953af36820bf44487a3ce7baf08e25e # v1.14.0
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

      - name: Build
        run: nix build -o result

      - name: Run vulnix
        uses: spotdemo4/vulnix-action@0dc86e0ad11bb6741e36803cb39984172df4af79 # v1.1.2
        with:
          path: result
          score: 7

  actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@8ea47d849953af36820bf44487a3ce7baf08e25e # v1.14.0
        with:
          shell: vulnerable

      - name: Run octoscan
        run: octoscan scan --verbose .github
