name: vulnerable

on:
  schedule:
    - cron: "0 9 * * 0" # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  svelte:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@081eaaf70d8590936c65966af8854d79d39f3108 # v1.8.12
        with:
          shell: vulnerable

      - name: Run npm audit
        run: npm audit --audit-level moderate

  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@081eaaf70d8590936c65966af8854d79d39f3108 # v1.8.12
        with:
          shell: vulnerable

      - name: Run flake-checker
        run: flake-checker -f

      - name: Build
        run: nix build -o result

      - name: Run vulnix
        uses: spotdemo4/vulnix-action@c614a37ec8850272bf58e0f821f3028aa32e5c4b # v1.0.1
        with:
          path: result
          score: 7

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@081eaaf70d8590936c65966af8854d79d39f3108 # v1.8.12
        with:
          shell: vulnerable

      - name: Run octoscan
        run: octoscan scan --verbose .github
