name: vulnerable

on:
  schedule:
    - cron: '0 9 * * 0' # every Sunday at 09:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@763ed4d8a4eb5dfc606b4127339042eb8dd685b2 # v1.8.0
        with:
          shell: vulnerable

      - run: npm audit --audit-level moderate

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: spotdemo4/nix-init@763ed4d8a4eb5dfc606b4127339042eb8dd685b2 # v1.8.0
        with:
          shell: vulnerable

      - run: flake-checker -f
